name: Random Time File Update

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs once every minute (GitHub's smallest allowed interval)
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Only triggers on pushes to the main branch
    paths-ignore:
      - '.github/workflows/update-file.yml'  # Ignore changes to this workflow file

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate Random Delay
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "SLEEP_TIME=$(( RANDOM % 86400 ))" >> $GITHUB_ENV
          else
            echo "SLEEP_TIME=0" >> $GITHUB_ENV
          fi

      - name: Simulate 15-second interval loop
        run: |
          for i in {1..4}  # Loop 4 times to simulate 15-second intervals, for 1 minute
          do
            echo "Updated on $(date)" > updated_file.txt
            git config --global user.name "ic334"
            git config --global user.email "${{ secrets.GH_EMAIL }}"
            git add updated_file.txt
            git commit -m "Auto-update file $(date)"
            git push origin main
            sleep 15  # Wait for 15 seconds before running the next iteration
          done
