name: Random Time File Update  # Name of the GitHub Actions workflow

on:
  schedule:
    - cron: '0 0 * * *'  # This schedules the job to start at midnight (UTC) every day
  workflow_dispatch:  # Allows manual triggering from GitHub Actions
  push:
    branches:
      - main  # Ensures that it only triggers on push to the 'main' branch
    paths-ignore:
      - '.github/workflows/update-file.yml'  # Prevents triggering on its own changes

jobs:
  update-file:
    runs-on: ubuntu-latest  # The workflow runs on the latest Ubuntu virtual machine

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # This pulls the latest version of the repository so we can modify files

      - name: Generate Random Delay
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "SLEEP_TIME=$(( RANDOM % 86400 ))" >> $GITHUB_ENV
          else
            echo "SLEEP_TIME=0" >> $GITHUB_ENV
          fi
        # Randomizes delay only if scheduled; runs instantly if manually triggered

      - name: Wait Random Time
        run: sleep $SLEEP_TIME
        # Waits for the randomly chosen number of seconds
        # Ensures the script runs at a different time every day

      - name: Modify File
        run: |
          echo "Updated on $(date)" > updated_file.txt
        # Updates the file 'updated_file.txt' with the current timestamp
        # If the file doesn’t exist, it will be created

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.GH_PAT }}  # Use the secret token for authentication
        run: |
          git config --global user.name "ic334"
          git config --global user.email "49622606+ic334@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/ic334/serious-business.git
          git add updated_file.txt
          git commit -m "Auto-update file"
          git push
        # Configures Git with your GitHub username and email
        # Adds the updated file, commits the changes, and pushes them to the repository using a Personal Access Token (PAT)