name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * 1-5'  # Every weekday at midnight UTC
  workflow_dispatch:  # Manual trigger to run the workflow

jobs:
  make-contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full commit history

      - name: Make daily contribution
        run: |
          # Example: Append the current date to a text file
          echo "Daily Contribution on $(date)" >> daily_contribution.txt


      - name: Commit and push
        run: |
          git config --global user.name "ic334"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git add .
          git commit -m "Automated daily update"
          git push
