name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * 1-5'  # Every weekday at midnight UTC
  workflow_dispatch:  # Manual trigger to run the workflow

jobs:
  make-contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the full commit history

      - name: Make daily contribution
        run: |
          # Example: Append the current date to a text file
          echo "Daily Contribution on $(date)" >> daily_contribution.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Isaac Cervantes"
          author_email: "${GH_EMAIL}"
          message: "Daily contribution"
          add: "daily_contribution.txt" 

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use your GitHub token for authentication

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution
          base: main
          body: "This pull request was created automatically by a GitHub Actions workflow to make a daily contribution."
          token: ${{ secrets.GITHUB_TOKEN }}  # Authentication token
