name: Random Time File Update  # Name of the GitHub Actions workflow

on:
  schedule:
    - cron: '0 0 * * *'  # This schedules the job to start at midnight (UTC) every day
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  update-file:
    runs-on: ubuntu-latest  # The workflow runs on the latest Ubuntu virtual machine

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # This pulls the latest version of the repository so we can modify files

      - name: Generate Random Delay
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "SLEEP_TIME=$(( RANDOM % 86400 ))" >> $GITHUB_ENV
          else
            echo "SLEEP_TIME=0" >> $GITHUB_ENV
          fi
        # Randomizes delay only if scheduled; runs instantly if manually triggered

      - name: Wait Random Time
        run: sleep 15
        # Waits for the randomly chosen number of seconds
        # Ensures the script runs at a different time every day

      - name: Modify File
        run: |
          echo "Updated on $(date)" > updated_file.txt
        # Updates the file 'updated_file.txt' with the current timestamp
        # If the file doesn’t exist, it will be created

      - name: Create New Branch for Update
      run: |
        BRANCH_NAME="daily-contribution-$(date '+%Y%m%d')"  # Fixing how the date is handled
        echo "Branch name: $BRANCH_NAME"  # Print the branch name for debugging
        git checkout -b "$BRANCH_NAME"  # Create a new branch with the evaluated date

      - name: Commit Changes
        run: |
          git config --global user.name "ic334"  # Ensure your username is used
          git config --global user.email "${{ secrets.GH_EMAIL }}"  # Ensure your email is used
          git add updated_file.txt
          git commit -m "Auto-update file $(date)"  # Commit with a more meaningful message

      - name: Push Changes to New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
        run: |
          echo "Pushing to branch: $BRANCH_NAME"  # Print the branch name to verify it's not empty
          git push origin "$BRANCH_NAME"  # Push the changes to the branch with the evaluated date

      - name: Open Pull Request (Using peter-evans)
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution-$(date +%Y%m%d)
          base: main
          body: "This pull request was created automatically by a GitHub Actions workflow to make a daily contribution."
          token: ${{ secrets.GITHUB_TOKEN }}
        # Citation: This action is used for creating pull requests automatically.
        # Source: https://github.com/peter-evans/create-pull-request
